[package]
name = "mice"
version = "0.1.3"
authors = ["Monadic Cat <greenmonadcat@gmail.com>"]
repository = "https://github.com/Monadic-Cat/mice"
description = "messing with dice"
license = "MIT OR Apache-2.0"
edition = "2018"

[dependencies]
nom = "5.0.0"
rand = "0.7.0"
