[package]
name = "mbot"
version = "0.1.0"
authors = ["Monadic Cat <greenmonadcat@gmail.com>"]
edition = "2018"
license = "AGPL-3.0-or-later"

[dependencies]
serenity = { git = "https://github.com/Lakelezz/serenity.git", branch = "await", features = ["framework", "standard_framework"] }
tokio = { version = "0.2", features = ["full"] }
mice = { git = "https://github.com/Monadic-Cat/mice", branch = "unstable-features" }
nom = "5.0"
rand = "0.7"

[features]
static_token = []

